### ISSUE TITLE
Centralize development coordination w/in GitHub

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/tech-and-check-alerts#1]
For efficient and manageable group development, we need a central coordination point for code, issues, internal documentation, and project planning. GitHub is a natural choice, but we should verify that it works for all stakeholders.

- [x] Create this repo
- [x] Get stakeholder buy-in to coordinate on GitHub
- [x] Create development milestones and project board (#3)

**Comment by slifty** [comment]
I think Asa is gonna be fine with us developing in this repo -- the question is ultimately just going to be "where should it live"

I'm hoping it will move to the tech and check repository soon so we can create a project board that spans all of the things we're going to have our fingers in.

**Comment by slifty** [comment]
Now that #7 is done, we've spun up a project board [over here](https://github.com/orgs/TechAndCheck/projects/1)
