### ISSUE TITLE
Some descriptors are not getting removed

### ISSUE THREAD

**Issue by slifty** [TechAndCheck/tech-and-check-alerts#116]
There are some descriptors that show up in attribution blocks, which break attribution extraction.

Example from: http://www.cnn.com/TRANSCRIPTS/1908/03/cnr.21.html

```
PLEITGEN (on camera): The Russians call this place the "Gateway to Hell" because it looks almost like the earth is crumbling and the underworld is coming to light. And there are fears in this region that fast erosion like this could destroy entire cities very soon.
```

Apparently we need to recognize (or strip out during preprocessing) lower-case parenthetical notes (e.g. `(on camera)`)

There is also a bug where only the first instance of (voice over) is actually being removed.

**Comment by reefdog** [comment]
Should that just be added to [`removeDescriptors()`](https://github.com/TechAndCheck/tech-and-check-alerts/blob/e1ac344c6281b1a367eaa9ed01c6e8a16efb2f66/src/server/utils/cnn.js#L61-L65)?

**Comment by slifty** [comment]
Yes -- I also think there is a bug in removeDescriptors which only removes the first instance of some descriptors.

**Comment by reefdog** [comment]
Outta curiosity, `removeDescriptor()` is removing party affiliation from names too, so `removeDescriptors('TED CRUZ (R): I have a beard.')` returns `TED CRUZ: I have a beard.` Is that expected/desired?
