### ISSUE TITLE
Stop storing results and errors in the scrape logs

### ISSUE THREAD

**Issue by slifty** [TechAndCheck/tech-and-check-alerts#137]
It was a fine idea at the time but the reality is that storing scrape results and errors is a LOT of space and if we really need it for debugging we can always re-run the scrape in our sandbox and play with the outcomes then.

The database balloons right now, but this will be corrected with #136, making this particular issue less urgent.

We still want to store the outcome of the scrape (success vs failure), likely just as a boolean.

**Comment by reefdog** [comment]
I think we should probably prioritize this. I just checked, and the `scrape_logs` table is 5.5GB on production. (For comparison, `claims` and `statement_logs` are 46MB and 48MB, respectively.)
