### ISSUE TITLE
Design data schema for claims

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/tech-and-check-alerts#14]
We need to store claims.

There's an existing [schema](https://github.com/oneroyalace/Tech-Check-Alerts/blob/master/db_create.sql) we can reference, but we should assess how much of that schema we want to directly replicate. For instance, can we normalize claim data into a common set of columns, with site-specific data in a JSONB column (or in a separate metadata table)?

**Comment by slifty** [comment]
[ClaimReview schema](https://schema.org/ClaimReview) might be relevant here as well.

**Comment by reefdog** [comment]
Looking at the [example](https://schema.org/ClaimReview#ClaimReview-gen-287), the bits that correspond to the source claim (rather than the review itself) are [`claimReviewed`](https://schema.org/claimReviewed) (text) and [`itemReviewed`](https://schema.org/itemReviewed).
