### ISSUE TITLE
Transcript links don't resolve in Firefox

### ISSUE THREAD

**Issue by slifty** [TechAndCheck/tech-and-check-alerts#143]
This is CNN, really -- it resolves in chrome -- but we should change the way transcript URLs are constructed to account for the problem:

[http://cnn.com/TRANSCRIPTS/1908/04/se.01.html](http://cnn.com/TRANSCRIPTS/1908/04/se.01.html) doesn't resolve well.

[http://transcripts.cnn.com/TRANSCRIPTS/1908/04/se.01.html](http://transcripts.cnn.com/TRANSCRIPTS/1908/04/se.01.html) does.

NOTE: this might be caused by HTTPSeverywhere but either way, lets use the less redirecty one.

**Comment by reefdog** [comment]
This afflicts Safari too! (Though yes with HTTPSEverywhere.) I forgot to bring it up.

**Comment by reefdog** [comment]
We should be sure to do this before launch.
