### ISSUE TITLE
Design data schema for subscriptions

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/tech-and-check-alerts#15]
Subscriptions (email addresses) are currently not stored in a database. We should do so.

Bear in mind we may want to support things in the future like subscribing only to certain topics, or having a subscriber-specific delivery schedule.

**Comment by reefdog** [comment]
We're going to use Mailgun's mailing lists for the forseeable future.

**Comment by slifty** [comment]
For some additional context -- we decided to use Mailgun's mailing lists for the forseeable future.

**Comment by slifty** [comment]
ok ok fine.  For actual context: we faced a choice of either having our application manage the various mailing lists, and sending individual emails out through the Mailgun API, or using Mailgun's mailing lists.

By using mailgun's lists we get subscription / unsubscription interfaces for free, we don't have to worry about batching the email blasts (if we provide individual emails we have to batch in sets of 1,000).

Once we decide to do fully personalized emails (e.g. individual users can indicate the topics of claim they care about, or subscribe to specific twitter lists, or select a custom time to get the mailings) it will make sense to revisit.

But, ultimately, we decided to use Mailgun's mailing lists for the forseeable future.

**Comment by reefdog** [comment]
@slifty Thank you much for providing that additional context (and apologies that I didn't).

**Comment by slifty** [comment]
@reefdog I really, really, really want to delete my note of actual additional context now.

**Comment by reefdog** [comment]
@everyone see what i have to work with

**Comment by reefdog** [comment]
@slifty I fail to see how that provides additional context considering you seem to have just copied and pasted what I wrote?

**Comment by slifty** [comment]
![0mKXcg1](https://user-images.githubusercontent.com/208884/58659346-bb70bb00-82f0-11e9-9007-628ca5519b70.gif)

**Comment by reefdog** [comment]
Thanks. I really achieved a rare clarity of expression up there. I can understand why you wanted to take credit for it.



_(I feel it imminently important to break character here and note for future historians that Dan and I have been playing a game of comment editing and deletion to troll each other, and he wrote the context block above that I retroactively added to my terse closing comment.) (Sorry to kill the joke with dissection, but I also hate for anyone to be out of the loop.)_
