### ISSUE TITLE
Set newsletter delivery to the appropriate time

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/tech-and-check-alerts#154]
Because our job scheduler is local timezone-dependent, the [`EVERY_MORNING`](https://github.com/TechAndCheck/tech-and-check-alerts/blob/703f9571e38fcfa3699dccc98fd3a74cb614d1a4/src/server/queues/constants.js#L6) delivery schedule is relative based on the timezone of the server that's doing the sending. We will eventually address that in #153, but for now we should offset `EVERY_MORNING` based on the actual production server running in UTC.

The only question is what time we actually want the newsletter delivered. The current newsletter is delivered at 8am Eastern, but I believe there was chatter about adjusting that.

So @markstencel @ericaryan: what time (Eastern) should we deliver the newsletter?

**Comment by ericaryan** [comment]
Unless @markstencel has other thoughts, I think we should stick with 8 a.m. That was an adjustment we made post-Tech & Check Conference. It used to be delivered at 10 a.m. Eastern.

**Comment by markstencel** [comment]
Totally concur: 8 a.m. ET. Will this just to standard/daylight savings, or is that part of #153?

**Comment by slifty** [comment]
I believe that the server we're using is hosted in EST so it should adjust to standard / daylight savings!

**Comment by reefdog** [comment]
I think it’s UTC, at least, that’s what `timedatectl` (or whatever, I’m mofile) reported. Presumably we can set the clock to Eastern though.

**Comment by reefdog** [comment]
@slifty Do you have any idea if the system clock affects whether Postgres stores times differently? Like personally I would rather it still store them as UTC, though I know it doesn't matter so long as it encodes the timezone into the string (and whatever reads/queries them knows how to deal with that).

**Comment by reefdog** [comment]
Okay after talking to some other smarties, the recommendation is that changing the system clock away from UTC is a headache waiting to happen. Which means currently we have to define our sending schedule in UTC terms, which would _not_ automatically adjust w/DST. 😵

I think the plan should be:

1. Leave the system clock in UTC.
2. Schedule the newsletter in UTC terms (`12`).
3. Try to get #153 done before DST ends (Nov 3).
4. Set ourselves a reminder for Nov 2 to tweak the schedule manually if we haven't gotten to #153.

**Comment by reefdog** [comment]
Scratch all this. Bull has timezone support, so we can skip right to Doing The Right Thing.
