### ISSUE TITLE
Running master on EC2 has issues

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/tech-and-check-alerts#162]
There's a lot of Slack backscroll behind this, but in summary: scheduling the current tasklist with `yarn queue:jobs:schedule` on our current EC2 setup triggers a host of issues, some of which could be environmental and some configuration. We scaled the instance up to `t2.large` for further testing (which gave us the RAM headroom particularly), though I scaled it back to `t2.small` before calling it a day. You'll want to re-scale-up (and maybe even add some more cores if you think CPU might be an issue).

1. **Bull:** `error.log` shows a ton of `Missing lock for job` entries. Perhaps [this section from the Bull docs](https://github.com/OptimalBits/bull#important-notes) would be useful.
2. **Redis:** `error.log` shows a lot of `Redis is configured to save RDB snapshots, but it is currently not able to persist on disk` entries
3. **Sequelize/Postgres:** The console shows huge batches of Sequelize connection timeouts.
4. **Promises:** The console shows a whole bunch of complaints about unresolved async functions from the Sequelize timeouts in (3), which really just means #119 is a thing.

If I'm watching things with `htop`, the CPU immediately pegs both cores at 100%, and RAM usage gradually increases until settling in around 5GB. Sometimes CPU use settles down to 0% for a while, but RAM usage never seemed to drop below ~3GB. The console would burst tons of those Sequelize timeout messages (and associated unresolved Promise complaints) periodically.

**Comment by reefdog** [comment]
BTW, I changed the schedule of the `CnnTranscriptPortalCrawlerJobScheduler` to `EVERY_HOUR` on the server (not committed to the repo) while testing this.

**Comment by slifty** [comment]
It took a bunch of digging but I believe I discovered the root cause.

The issue stems from a misunderstanding about the way Bull handled concurrency.  In short: Bull creates child processes equal to the concurrency setting EVERY TIME you run .process on a queue object.  Because of the way that our QueueFactory worked we were doing that every time a queue was requested (even if the only purposes was to insert new jobs).

A PR is incoming to fix this.

**Comment by reefdog** [comment]
We can close this now, yeah? Yeah?

**Comment by slifty** [comment]
Lets wait until it really runs but I think so.

**Comment by reefdog** [comment]
lol fair. Offense, false start. Five-yard penalty, repeat third down.

**Comment by slifty** [comment]
Looks like we're all set!  Yay!
