### ISSUE TITLE
Should "TEXT" claims be processed?

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/tech-and-check-alerts#163]
Some transcripts contain sentences attributed to `TEXT`, which I assume means on-screen text. [Example:](http://www.cnn.com/TRANSCRIPTS/1908/14/wrn.01.html)

> TEXT: Jeffrey Epstein Indicted: Florida multi-millionaire; Accused of operating sex trafficking ring to lure minor girls; "Dozens" of victims as young as 14 years old; Would pay victims to recruit other victims; Some victims were abused for years

Should we process these for claims? I'm assuming not, but if so, who should we consider to be the speaker? The show itself?

**Comment by markstencel** [comment]
We should not. It's possible a statement would be turned into on-screen text -- an official statement that hosts and guests might also read or discuss. But it's more likely to be like the example you shared -- an on-screen caption that will generally not be of use to fact-checkers.

**Comment by reefdog** [comment]
@markstencel Perfect, thanks! Task opened as #164.
