### ISSUE TITLE
Set up database and Node access

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/tech-and-check-alerts#17]
- [x] Create database
- [x] Set up access controls
- [x] Create sample config files
- [x] Choose/implement a migrations system
- [x] Add/configure Node access
- [x] Add setup instructions to README
- [x] Add migration instructions to README

**Comment by slifty** [comment]
Sequelize is basically the standard ORM / migration system in Node so I'm gonna just set that up.

I'm going to also create an AWS RDS for production -- given the nature of the tool I'm not convinced we will want a shared dev RDS.

**Comment by reefdog** [comment]
Feel free to split migrations off to its own issue if that's going to be a Whole Deal.

**Comment by slifty** [comment]
I'm gonna call:

Create database
Set up access controls

as something a bit different more related to setting up the production server.
