### ISSUE TITLE
Claimbuster breaks when the statement is wildly long

### ISSUE THREAD

**Issue by slifty** [TechAndCheck/tech-and-check-alerts#170]
It seems some CNN transcripts can have really long uninterrupted comments (e.g. in a speech) which our parser treats as a single statement right now.

For [example](http://transcripts.cnn.com/TRANSCRIPTS/1908/19/cg.01.html): 

> Thank you so much to my dear friend and colleague, Congresswoman Ilhan Omar for inviting me to her district to join y'all today.   I'm incredibly thankful for her leadership and strength through all she has been dealing with as a woman of color in Congress.  I don't know how she does it sometimes, but the outpouring of support we have received from our constituents and supporters across the country shows us how important it is to keep fighting for justice.   Today's -- today, Reps Omar and Plaskett and I were supposed to be on a congressional trip and delegation to the Palestine and Israel and such delegations are common occurrence for members of Congress. Earlier this month, in fact, 71 other members of Congress traveled to Israel seemingly without incident.  What is not common occurrence as members of Congress being barred from entering a country on these fact-finding missions unless they agree to strict set of rules curtailing rights or being required to submit their itineraries for stop by stop pre-approval.   History does have a habit of repeating itself.  I learned this week that a former member of Congress, Congressman Charles C. Diggs Jr. was denied entry into apartheid South Africa in 1972.  He was also the representative for the 13th congressional district in Michigan.   I was born and raised in the beautiful Detroit, where many of my African-American teachers taught me about the realities of oppression and justice and the need to speak up and take action.  Growing up in a city that has been at the center of many social justice movements for civil rights, labor rights and equality and absorbing those lessons has shaped who I am today, and drives me to push for peace and justice for the Palestinian and Israeli people.  As a young girl visiting Palestine to see my grandparents and extended family, I watched as my mother had to go through dehumanizing checkpoints -- even though she was a United States citizen and proud American.  I was there when my city was in a terrible car accident and my cousins and I cried so she could have access to the best hospitals which were in Jerusalem.  I remember shaking with fear when check points appeared in the small village of Beit Ur al-Fauqa, tanks and guns everywhere.   I remember visiting East Jerusalem with my then-husband and him escorted off the bus, although he was a United States citizen just so security forces could harass him.  All I can do as my city's granddaughter, as the granddaughter of a woman who lives in occupied territory is to elevate her voice by exposing the truth, the only way I know how.  As my Detroit public schools teachers taught me, by humanizing the pain of oppression, our delegation trip included meetings with Israeli veterans, who were forced to participate in military occupation.  They also desperately want peace and self-determination for their Palestinian neighbors.  They could have shed light into injustices of raids, shootings and demolition and child detention.   The delegation would have seen firsthand why walls are destructive and not productive.  They could have asked the people in Bethlehem how walls cut people off away from economic opportunities from a way to live and do psychological damage that lasts forever.  All I can do as her granddaughter is help humanize her and the Palestinian people's plight.  I know that when we could finally see them as deserving of human dignity, everyone who lives there will be able to live in peace.  It is unfortunate that Prime Minister Netanyahu is apparently taken a page out of Trump's book.  And even direction from Trump to deny this opportunity.  And, yes, while folks are shocked this happened to us, but today we will hear from folks who helped show the reality for many who have been barred from going to Israel, not to be even able to reach the Palestinian people.  They are fellow Americans who cannot visit their families or their loved ones.   They should be -- all of us should be deeply deserved, all Americans should be deeply disturbed and with that I thank you so much to my colleague Congresswoman Ilhan Omar for helping humanize the Palestinian people.

We either need to split these into smaller chunks, or we need to see if claimbuster v2 offers an alternative approach to querying, which will happen with #139.

**Comment by reefdog** [comment]
Confirmed that the V2 API doesn't break on that amount of text, when using the POST method (which we are). Thus, #217 will resolve this. :tada:
