### ISSUE TITLE
Add sources and date to email subject line

### ISSUE THREAD

**Issue by ericaryan** [TechAndCheck/tech-and-check-alerts#184]
We'd like to maintain the subject line that exists on the current email alerts:

Example:
Tech & Check Alerts: Twitter, CNN 08/22/19

We think this is helpful for fact-checkers who archive these emails.

**Comment by reefdog** [comment]
So to be clear, the date should be `MM/DD/YY`? With leading zeroes on the months and days and with two digits only for the year? (It's trivially easy to change this format.)

**Comment by ericaryan** [comment]
I have no preference on the date display! Just as long as it's easily understood. @markstencel, do you have thoughts?

**Comment by reefdog** [comment]
Okay, cool. My programmer's preference is for `YYYY-MM-DD` (e.g., "2019-08-22") for better sorting and so we don't have to exasperate our allies with an M/D/Y vs. D/M/Y war if we ever expand beyond the US, but it's also a bit roomy, so the more collapsed form (even down to the non-leading-zero version `M/D/YY`, e.g. "8/1/19").

Anyway your call, just making sure!
