### ISSUE TITLE
Ensure services come back online automatically after reboot

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/tech-and-check-alerts#193]
Rebooting the server should restart all services: Postgres, Redis, etc.

Should it automatically start the app? I think probably not…? Feels like something we'd want to be sure to kick off manually, since a consequence of this is real people getting emails.

Anyway let's verify this all works as expected!

**Comment by reefdog** [comment]
Counterpoint: it should start the app automatically. This is a scraper machine and it needs to start scraping. Newsletters are scheduled for a fixed time once every 24 hours, which gives us lots of time to disable them upon reboot if we want. (And if it was an unmonitored reboot, we definitely want things to pick up as they were.)

**Comment by slifty** [comment]
Counterpoint: it should start the app automatically. This is a scraper machine and it needs to start scraping. Newsletters are scheduled for a fixed time once every 24 hours, which gives us lots of time to disable them upon reboot if we want. (And if it was an unmonitored reboot, we definitely want things to pick up as they were.)

**Comment by reefdog** [comment]
That's such a good counterpoint.

**Comment by slifty** [comment]
Just to follow up on my excellent idea above -- we can always stop the service if desired; ideally instead of simply "starting on reboot" we would have the goal be "maintain state on reboot"

That way if we do want to stop to tinker, and then reboot, the service would not spin up in ways we don't want or expect.

**Comment by reefdog** [comment]
I see what you're saying but really feel like you maximized the articulation of your idea with your first comment.

**Comment by slifty** [comment]
[looks like maybe pm2 doesn't quite support that as automagically as it could](http://pm2.keymetrics.io/docs/usage/startup/)

It seems like you "lock in" a configuration and if you ever want to update the startup list you have to manually do so using `pm2 save`

I don't think this kind of documentation will belong in our repo, but I will add it to the README of the server itself.

**Comment by slifty** [comment]
The new AMI is now configured to restart pm2 and its processes on boot.

Dev and prod are set up that way now as well.
