### ISSUE TITLE
Update boilerplate copy with time range note

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/tech-and-check-alerts#208]
We want to add a note to the newsletter boilerplate that the claims are "from the past 24 hours".

Assigning this to @markstencel and @ericaryan to decide where exactly that bit should go, then re-assign to me to implement!

**Comment by ericaryan** [comment]
Mark has OK'd my suggestion for this here: https://docs.google.com/document/d/10y61X0I6cVbzirozDTjrpqFZk8fTi_k5Ortw0OPY9qg/edit?usp=sharing
