### ISSUE TITLE
Set up common parse tooling

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/tech-and-check-alerts#21]
Following on from #20, this should receive the scraped content and:

- [ ] Pass it to the ClaimBuster API
- [ ] Recover from (or have a retry plan) for ClaimBuster API errors
- [ ] Write results to the database (#17)

**Comment by slifty** [comment]
My thinking on this is that claimbuster interaction should be in the form of its own worker thread / queue.

**Comment by reefdog** [comment]
So essentially then, we don't need a generic parsing template, because the worker/queue pattern we've already got essentially is that. Wanna just rename/reframe this as "okay, now pass claims to ClaimBuster"? (Which is what the body of this task was about, but the framing was "demonstrate a generic pattern for doing so", which isn't any use now.)

**Comment by slifty** [comment]
Yeah I think that's a good plan -- I'll do that reframing when I pick this up.

**Comment by slifty** [comment]
Narrator: He didn't do that reframing.
