### ISSUE TITLE
Provide boilerplate copy for NC newsletter

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/tech-and-check-alerts#212]
We need updated boilerplate intro (and possibly "About") copy for the NC newsletter. (Breaking this out of [#94](https://github.com/TechAndCheck/tech-and-check-alerts/issues/94#issuecomment-523609196).)

**Comment by ericaryan** [comment]
I checked in with Mark about this a day or two ago and it was still pending! I will mention it again

**Comment by ericaryan** [comment]
Text is here: https://docs.google.com/document/d/1RSq95FB8o0sPCOgMGluqlpURPnFUcjcIGDP03kpEmHk/edit?usp=sharing

**Comment by reefdog** [comment]
Got it!
