### ISSUE TITLE
Port Twitter scraping

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/tech-and-check-alerts#26]
Most important feature: preserve emoji in speaker names, content, etc.

**Comment by reefdog** [comment]
We've currently got two lists of Twitter accounts to scrape: general and NC-specific.

**Comment by slifty** [comment]
Twitter scraping is now real; the main thing that is not ported is the synchronization of externally defined twitter list with our scrape pipeline (so: the google doc sync).

I'll leave this issue open for now, but that may be turned into a separate issue in which case I will close this one.

**Comment by reefdog** [comment]
Syncing opened as #229, so calling this done with further refinements opened as individual issues.
