### ISSUE TITLE
Check scrape horizon before querying database

### ISSUE THREAD

**Issue by emilyliu7321** [TechAndCheck/tech-and-check-alerts#277]
When scraping CNN transcripts, we [currently check first](https://github.com/TechAndCheck/tech-and-check-alerts/blob/6f98c7372b687fcf295fbd6aa3a960de08db28d0/src/server/queues/cnnTranscriptListCrawlerQueue/cnnTranscriptListCrawlerJobProcessor.js#L17-L20) for if a transcript has previously been scraped before checking if it is beyond our scrape horizon. This means that we query the database each time. 

We should swap the order of the conditions for efficiency.

**Comment by reefdog** [comment]
This is a great optimization that will be easy to do. But quick question for @slifty: should we be checking `getMostRecentSuccessfulScrapeTime()` [here](https://github.com/TechAndCheck/tech-and-check-alerts/blob/6f98c7372b687fcf295fbd6aa3a960de08db28d0/src/server/queues/cnnTranscriptListCrawlerQueue/cnnTranscriptListCrawlerJobProcessor.js#L15)? Right now we're just checking if there's been _any_ scrape, even if it failed; shouldn't we only bail out if the scrape was successful? (It'll eventually fall off the date horizon anyway.)
