### ISSUE TITLE
Suggest design/usability improvements to email template

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/tech-and-check-alerts#28]
It's possible the existing templates require no improvements, but perform a design pass for usability, layout, styling, content, and language improvements.

**Comment by reefdog** [comment]
Suggested template:

![email-template](https://user-images.githubusercontent.com/4731/61155552-d4a38480-a4b6-11e9-82a9-ee5ac631e1b1.png)

- Content has a maximum line width of 40em so there's no really long text lines
- Typography tries to draw attention to relevant things

Open question: how do we want to phrase and link the attribution? I gave several distinct options. For Twitter, we could link just "claimed" or the entire "[Speaker] claimed". For CNN, we have speaker and show, so there are three variations. Cast your vote!

**Comment by slifty** [comment]
This looks great (and so much cleaner than the current template)!

One thought: So, the primary use case of this is quickly*scanning* for the claims, and people will generally be highly trained / trainable.  This means the explanations are important, but ultimately noise.

I think maybe this layout reads more like a newsletter than a tip sheet (@ericaryan I look to you to weigh in though.)

I wonder if we can do more to draw attention to the distinct claims, maybe using emoji or bullets?

One thing that was good about the table layout before was that scanning was fast.

**Comment by reefdog** [comment]
Totally agree on all points! I'd love to be able to put all the boilerplate about Twitter/CNN sourcing at the bottom in a single "reminders" section. I'd also love to be able to intermix Twitter and CNN claims and just distinguish them through labels or (as you mention) iconography.

**Comment by reefdog** [comment]
Here's a very fast reworking that just changes type size and weight, and moves attribution below the quote, to improve scannability. I'd still love to move the boilerplate:

![Screen Shot 2019-07-12 at 3 26 23 PM](https://user-images.githubusercontent.com/4731/61156615-6d3b0400-a4b9-11e9-88af-6754b6daf6ad.png)

**Comment by reefdog** [comment]
Speed-redesign given @slifty's great feedback:

![email-template-2](https://user-images.githubusercontent.com/4731/61157319-6ca36d00-a4bb-11e9-87f1-83fb222025d2.png)

**Comment by slifty** [comment]
<img width="625" alt="image" src="https://user-images.githubusercontent.com/208884/61157384-00793700-a4c4-11e9-8479-e3601e770a8c.png">
Excuse me: how is this at all about birds.

**Comment by reefdog** [comment]
WVGOP stands for Wing Velocity Grand Old Peregrine.

**Comment by ericaryan** [comment]
This looks very nice! And I love the emoji! 

My concern with mixing is that we have generally found CNN claims to be more useful, even when having lower ClaimBuster scores, than Twitter claims. So we might be watering down the most useful stuff to fact-checkers by mixing them together. (As in, they might currently be reading CNN claims more carefully and then just skimming Twitter more quickly.)

@markstencel Is the guy responsible for the boilerplate, so I will let him weigh in on that as well as the design possibilities. I'm fine with moving it to the bottom, personally, since I agree no one is likely reading it after their first day receiving the email, but it's important to have it somewhere.

**Comment by reefdog** [comment]
Ah, that's excellent to know!

If keeping platforms distinct is an important feature of the newsletter, we can definitely keep doing that. I do wonder if the emoji adds enough distinction that folks who do care mostly about CNN can just scan for the 📺 without requiring us to actually do blocks, but obvs I'm open to whatever is best.

A real big question I have is if **speaker scannability** needs improvement. Putting speakers in their own column makes them more scannable, but generates lots of unused real estate. So feedback there is definitely appreciated.

**Comment by reefdog** [comment]
Oh, and on the reminder text: I experimented with additional ways of calling special attention to certain phrases, like the all-important "check the original post to verify attribution":

![Screen Shot 2019-07-12 at 5 35 37 PM](https://user-images.githubusercontent.com/4731/61161868-7c2ab200-a4cb-11e9-8444-fe38dd18b316.png)

That's probably a bit more glaring than we need, but just to show we can definitely call attention to it even in a diminished position.

**Comment by reefdog** [comment]
Added coloring to "Twitter" and "CNN" to call even more attention:

![now-with-colors](https://user-images.githubusercontent.com/4731/61162584-e3963100-a4ce-11e9-8a66-b33b27c9e5c5.png)

**Comment by markstencel** [comment]
Apologies for being late to the party here!

What I love most: short text up top with all the details at the bottom (Erica and I can re-draft wording with that in mind); emojis :-) ; overall readability. What an improvement.

Questions: I really like the color-coded source (in CNN red and Twitter blue). What will be do for other sources once we add them (MSNBC/NBC, Fox, Congressional Record, Facebook)? I do not think we should NOT mix Twitter with CNN for the reasons Erica mentioned, but I do kind of like the idea of mixing TV sources once we add more. Will that mean we need to display more results in each newsletter, since some of the claims that have caught fact-checkers' eyes were not the highest scoring claims? Maybe. Not an immediate issue since we do not yet have any other TV sources. Also, the quality of what we send may improve if/when filtering out speakers who have not yet been fact-checked (based on ClaimReview). If possible, I would love to put CNN/TV claims first, unlike our current newsletter which starts with tweets. 

Sorry again for this belated input. Happy to translate if any of this is indecipherable.

**Comment by reefdog** [comment]
Thanks @markstencel! That feedback is good and perfectly decipherable.

> I do not think we should NOT mix Twitter with CNN for the reasons Erica mentioned.

Cool, I'll break them back out.

> I really like the color-coded source (in CNN red and Twitter blue). What will be do for other sources once we add them (MSNBC/NBC, Fox, Congressional Record, Facebook)?

I plan for each one to use exactly the brand color for that platform. (For instance, I didn't just pick any red and blue; I nabbed the colors straight from the respect CNN and Twitter branding.) Many of them have very similar brand colors, but I _think_ that's okay; the brand name is the primary differentiator, while color is just a bit of pizazz. If that ends up looking too wrong or confusing, we can definitely remove it. (Or experiment with adding actual logomarks, but I smell that getting visually chaotic.)

> If possible, I would love to put CNN/TV claims first, unlike our current newsletter which starts with tweets.

Definitely!

I've implemented your feedback into this mockup, lemme know what you think. With the claims unthreaded, the per-claim emoji was a little noisy (just a row of TVs and then a row of birds), so instead I'm using them in the section headers. I'm also using platform-agnostic header names, even though we currently only have one platform per medium. This way we already have our pattern down for mixing Fox/etc. into CNN and mixing Facebook in with Twitter.

![email-template](https://user-images.githubusercontent.com/4731/61327508-ac7d9380-a7de-11e9-93b0-288ec4ab6503.png)

**Comment by reefdog** [comment]
Two more notes:

1. Of course it's super easy to change copy, so please feel free to edit the boilerplate as much as you want! This is also HTML email, so if bolding or highlighting will help draw attention to Very Important Passages, feel free to do so.
2. Using Mailgun mailing lists lets us add unsubscribe links to emails if we want. If we do so, I'd recommend adding a "You can always unsubscribe in one click." link as the last sentence in the opening "**Good morning, fact checkers!**" paragraph.

**Comment by reefdog** [comment]
Here's a quick example of using the brand colors for each claim, this time both the platform name and the border of the claim content:

![email-template-brands](https://user-images.githubusercontent.com/4731/61329909-06348c80-a7e4-11e9-8d3d-5a28d79e0ab6.png)

I'm kind of leaning toward only doing the border color; that way the name itself is there for reading, but isn't drawing too much attention away from the claim itself:

![email-template-brands-subtle](https://user-images.githubusercontent.com/4731/61330007-409e2980-a7e4-11e9-852a-99ce5976c03a.png)

**Comment by reefdog** [comment]
I'm kind of leaning toward only doing the border color; that way the name itself is there for reading, but isn't drawing too much attention away from the claim itself:

![email-template-brands-subtle](https://user-images.githubusercontent.com/4731/61330007-409e2980-a7e4-11e9-852a-99ce5976c03a.png)

**Comment by slifty** [comment]
FWIW I like it better with color on the name too -- easier to scan and more obvious what the use of color is associated with.

**Comment by reefdog** [comment]
Definitely easier to scan for that platform, but then once you're reading the claims, does it keep trying to steal your eye? The brighter ones especially (Twitter, MSNBC) keep doing that to me. 🤔

**Comment by slifty** [comment]
What if we just make the background AND the text also be the color to avoid the distraction.

I made a mockup:

<img width="683" alt="image" src="https://user-images.githubusercontent.com/208884/61330962-d8a11080-a7ee-11e9-98b6-1f7ab94c8bcd.png">

**Comment by reefdog** [comment]
That's an amazing idea. I was just making another great idea over here, I think with these two changes we're ready for print:

![28-tasteful-decoration](https://user-images.githubusercontent.com/4731/61330942-67f5f600-a7e6-11e9-8d6c-9d5914b0eada.gif)

**Comment by markstencel** [comment]
Blinking scroll is a MUST. With Drudge sirens?

Source colors are great. Will think about the text and get back to you. Thank you!

**Comment by slifty** [comment]
We've outdone our selves, ready to ship.

A real exploratory thought (not that that last idea wasn't real obviously):

1. What about a color underline under the source that is different form the text (so CNN would have a red underline; or heck maybe even the whole underline?)
2. What about making the station name smaller but still bold and colored in?

**Comment by reefdog** [comment]
> What about a color underline under the source that is different form the text (so CNN would have a red underline

Assuming you mean CNN's text would be in gray but with a red underline, here's how that looks:

![cnn-only](https://user-images.githubusercontent.com/4731/61331656-e30bdc00-a7e7-11e9-83a6-f4aadf92d6f5.png)

> heck maybe even the whole underline

And here's how that looks:

![entire-permalink](https://user-images.githubusercontent.com/4731/61331668-e8692680-a7e7-11e9-86dd-4f4bae775f64.png)

> What about making the station name smaller but still bold and colored in?

That looks kinda cool (though I still think in total, we bump into the distractability problem):

![small-platform](https://user-images.githubusercontent.com/4731/61331790-39791a80-a7e8-11e9-920f-c939460a4200.png)

**Comment by slifty** [comment]
One additional thought: instead of chaining "on" lets consider

PERSON NAME on SHOW NAME (NETWORK/WHATEVER)

**Comment by reefdog** [comment]
I like "via" for social media and "on" for TV, I think? And yes, I also like putting TV channel in parentheses rather than a chain of ons!

**Comment by markstencel** [comment]
re: show name. Transcripts like this currently generate a "show not found" in our alerts. http://transcripts.cnn.com/TRANSCRIPTS/1907/11/crn.01.html I don't know if that's because the current process depends on a list of shows that's outdated, if the transcript intentionally or unintentionally does not include a show title or what.

PERSON NAME on SHOW NAME (NETWORK/WHATEVER) is OK by me, though you will get a lot of...

ELIZABETH WARREN on CNN NEWSROOM (CNN)

...which is probably fine.

**Comment by markstencel** [comment]
CNN show names don't matter all that much for fact-checking purposes. But it will matter once we have other networks, especially MSNBC and Fox, so good to have them.

**Comment by reefdog** [comment]
I'm gonna close this. We've had enough buy-in to the new layout that we'll call it "good enough to bug-report on". I'll create new issues for the remaining individual pieces.
