### ISSUE TITLE
Migrate existing claims

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/tech-and-check-alerts#33]
Are we going to migrate in existing claims? If so they'll need to conform to our new schema (if it deviates from existing). Note: this likely relies on the answer to #37.

**Comment by ericaryan** [comment]
I'm not 100% sure this is relevant here, but I wanted to note that our unofficial legal adviser has advised us not to store/database claims from copyrighted transcripts like the CNN ones. Storing the emails themselves may be OK.

**Comment by reefdog** [comment]
Oh yes, this is very relevant! And definitely something we need to capture in our design. Can you open a new issue for it @ericaryan? Something like "Determine data retaining rules and procedures"?

**Comment by slifty** [comment]
@ericaryan Wanted your thoughts on this -- my guess is that we do NOT need to migrate over past claims.

**Comment by ericaryan** [comment]
@slifty Let's discuss on our call tomorrow, as I'm actually not sure!

**Comment by reefdog** [comment]
Definitely not a need, according to conversations.
