### ISSUE TITLE
Known speaker scraper doesn't populate scraper name in scrape log

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/tech-and-check-alerts#330]
When running the known speaker scraper (`yarn queue:jobs:run:known-speaker-scraper`), the `scrape_logs` entry generated has `scraper_name = NULL`.

![Screen Shot 2020-02-25 at 5 42 36 PM](https://user-images.githubusercontent.com/4731/75297764-4fc36c00-57f6-11ea-851e-250020db4abf.png)

**Comment by slifty** [comment]
![image](https://user-images.githubusercontent.com/208884/77330231-6b3a6d80-6cf5-11ea-858a-6f507787d92c.png)
