### ISSUE TITLE
Set up Minnesota Alert (a la North Carolina)

### ISSUE THREAD

**Issue by ericaryan** [TechAndCheck/tech-and-check-alerts#349]
We will be implementing a new Alert to send to fact-checkers in Minnesota with Twitter claims, like the North Carolina list.

We are working on:
-Twitter list of Minnesota speakers
-Mailing list of Minnesota journalists

@markstencel Anything to add?

**Comment by reefdog** [comment]
It took a long time, but I'm proud to see this one finally finished and to say I played a role in closing this issue.

**Comment by reefdog** [comment]
We did good, Dan. We did good. This is truly a team effort.

**Comment by reefdog** [comment]
Whew, this one’s taking a bit more effort than I expected, but I’m finally able to call it done!
