### ISSUE TITLE
Don't allow "twitter_%d" as a valid twitter column header

### ISSUE THREAD

**Issue by slifty** [TechAndCheck/tech-and-check-alerts#357]
In #355 @reefdog suggested and approved the use of the literal string `twitter_%d` to be considered a valid twitter column in a twitter spreadsheet during the sync process.  I went along with it at the time, but after reflecting I'm not sure this makes sense to support.

Lets modify the `isTwitterDisplayNameColumn` helper method to remove [support for matching that particular literal](https://github.com/TechAndCheck/tech-and-check-alerts/blob/e50a54976f17e5966f79105b6f539245a70c53e0/src/server/queues/twitterAccountListScraperQueue/twitterAccountListScraperJobProcessor.js#L20).

![image (7)](https://user-images.githubusercontent.com/208884/80822780-6ea0fe80-8ba9-11ea-80c8-9a184fd0ca30.png)

**Comment by reefdog** [comment]
I am filled with shame and deserved this.

**Comment by slifty** [comment]
Following up here cc @reefdog should be a quick fix.

**Comment by reefdog** [comment]
Totally agree and the assigned person should be able to handle it real quickly.
