### ISSUE TITLE
Deploy to production

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/tech-and-check-alerts#36]

**Comment by cguess** [comment]
Should also upgrade Mailgun at the same time.

**Comment by reefdog** [comment]
Are we on an old version?

**Comment by cguess** [comment]
Just a "concept" plan. They're trying to upsell me it turns out (I just went and looked) and no, we don't need the bigger ones. The biggest issue would be only 5 days of logs. But we can always just consume those and save our.s

**Comment by reefdog** [comment]
Oh, upgrade the account type. Gotcha. I thought you meant, like, the version of the API or the mailgun-js package or something.

**Comment by slifty** [comment]
I believe this is actually complete -- open back up if I'm wrong!
