### ISSUE TITLE
Set up automated testing

### ISSUE THREAD

**Issue by slifty** [TechAndCheck/tech-and-check-alerts#39]
We should be writing tests as we write components.  This will be much easier to do up front than it will be to retrofit automated testing.

This issue is about setting up the test framework and incorporating it into CI, not actually writing tests for any code that has been written so far (that should be made as separate issues if it applies).

* [x] Lets use ~[mocha](https://mochajs.org/) and [chai](https://www.chaijs.com/)~ [Jest](https://jestjs.io)
* [x] Lets have travis CI run the tests

**Comment by slifty** [comment]
@ericaryan @markstencel Testing notifications

**Comment by reefdog** [comment]
So, I was able to install and configure Mocha and Chai, but they were a headache. I then stashed that and gave [Jest](https://jestjs.io/) a try, and it was _so much easier_ and faster to get started. I also prefer its assertion syntax; it's a small thing, but `expect(foo).toEqual(bar)` seems much more JavaScripty than `expect(foo).to.equal(bar)`, which starts to feel too clever by half.

I really like some of the patterns Jest comes out of the box with, like looking for `__test__` directories and `Blah.test.js` files, which allows us to do things like put tests alongside the classes or workers or components or whatever that they're testing.

What do you think?

**Comment by slifty** [comment]
Jest sounds great to me!

**Comment by reefdog** [comment]
For the Travis CI bit, do I just add this to the `scripts` array of `.travis.yml`?

```
  - npm run test
```

**Comment by reefdog** [comment]
Okay I think that did it. I suppose I should write some failing tests to verify. Lemme do that, and keep them as part of the commit history to PROVE IT.

**Comment by reefdog** [comment]
Woohoo!
<img width="766" alt="failing-travis-build" src="https://user-images.githubusercontent.com/4731/58359699-69401d80-7e4a-11e9-932d-431402920815.png">
Okay, gonna remove the test.
