### ISSUE TITLE
Confirm domain with Mailgun

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/tech-and-check-alerts#61]
To send mail from an `@reporterslab.org` email address and create mailing lists like `newsletters.national@reporterslab.org` (or whatever), we need to [confirm our domain w/Mailgun](https://help.mailgun.com/hc/en-us/articles/360011565514-How-Do-I-Verify-My-Domain-and-Other-DNS-Questions). This requires DNS verification, though it's just a TXT, not pointing MX (of course).

If for some reason we don't want to actually use `@reporterslab.org`, we could do a subdomain like `@newsletters.reporterslab.org` or something.

**Comment by reefdog** [comment]
Hey @cguess, think this'll be something you can tackle soon? Any concerns/questions about it?

**Comment by cguess** [comment]
On it now. Travel's been a bitch, and no wifi on a single flight!

-Christopher Guess
cguess@gmail.com
US/WhatsApp/Signal: +1 262.893.1037
PGP: AAE7 5171 0D82 B45B

**Comment by cguess** [comment]
Do you need @reporterslab or is @sharethefacts or @factstream ok?

-Christopher Guess
cguess@gmail.com
US/WhatsApp/Signal: +1 262.893.1037
PGP: AAE7 5171 0D82 B45B

**Comment by reefdog** [comment]
Whatever y’all want! I was just assuming.

**Comment by slifty** [comment]
One thought: from a product / branding perspective I think reporterslab is the right address, just because we probably don't want to dilute the sharethefacts and factstream brands (unless we consider alerts to be part of one of those two projects!).

**Comment by cguess** [comment]
I need to confirm with the others (reporterslab.org is the one domain I don’t control)

**Comment by cguess** [comment]
alerts.factstream.co is being verified now. I'll close when confirmed.

**Comment by reefdog** [comment]
Eight days on and its still not found. Could you check them again on the DNS side, @cguess?

![mailgun-dns](https://user-images.githubusercontent.com/4731/60620074-d62ac980-9d9f-11e9-8d35-d59acb351f9e.png)

**Comment by cguess** [comment]
Ug.... I’ll check it out. Sorry I thought this was working.

**Comment by reefdog** [comment]
@cguess Still not working, 😬. Do we need to escalate something w/Mailgun or the DNS service?

**Comment by cguess** [comment]
Let me see...

-Christopher Guess
cguess@gmail.com
US/WhatsApp/Signal: +1 262.893.1037
PGP: AAE7 5171 0D82 B45B

**Comment by cguess** [comment]
OK, i've looked into. The records are correct. My guess is that it may be
because of the subdomain (alerts.factstream.co).

Yep, for some reason alerts.factstream.co is pointing to heroku's DNS, not
ours.

@reefdog Are y'all hosting this on Heroku at the moment?

-Christopher Guess
cguess@gmail.com
US/WhatsApp/Signal: +1 262.893.1037
PGP: AAE7 5171 0D82 B45B

**Comment by cguess** [comment]
Mailgun's instructions are dumb, and I forgot basic DNS maintenance. Fixed.
