### ISSUE TITLE
Choose and create a "from" address

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/tech-and-check-alerts#78]
Our newsletters need a from address, which needn't be (but no reason not to be) the reply-to address as well. Currently they just come from asa@asaroyal.com.

I'd recommend `support@{domain}` where `{domain}` is whatever domain we choose to use here, [currently looking like `alerts.factstream.co`](https://github.com/TechAndCheck/tech-and-check-alerts/issues/61). (I think `reporterslab.org` would be great, but doesn't sound like we have as much flexibility using that domain.)

This doesn't actually _need_ to be a real mailbox; we won't actually be sending through it with SMTP or anything. But it should be able to receive email in case people hit "reply" to an alert to ask us a question. A (non-Mailgun) mailing list with several team members on it is probably best.

**Comment by ericaryan** [comment]
@cguess Do you want to make a FactStream support address that we can use instead of team@sharethefacts.org?

**Comment by reefdog** [comment]
Bump @cguess, could we setup team@alerts.facstream.co (or whatever y'all want) to use as the from address? I'm like 90% sure this is just for the email headers and won't actually be used for SMTP or anything, but of course it should receive/forward mail for if subscribers reply to the alert.

**Comment by cguess** [comment]
alerts@factstream.co it is!

**Comment by slifty** [comment]
We had a hefty conversation on call about this -- felt that there was no major benefit of a subdomain at this point. 

If things get high volume later we can revisit.

**Comment by reefdog** [comment]
Awesome y'all, thanks!

Reopening real quick: what we do want the visible from name/label to be? "Duke Reporter's Lab Alerts"?

**Comment by ericaryan** [comment]
Tech & Check Alerts <alerts@factstream.co>

**Comment by reefdog** [comment]
Sounds good!
