### ISSUE TITLE
Address lodash vulnerability

### ISSUE THREAD

**Issue by slifty** [TechAndCheck/tech-and-check-alerts#81]
Lodash amirite?

Looks like some of our dependencies require a version of lodash with a critical vulnerability.  Lets try to fix this by either updating those dependencies.

**Comment by slifty** [comment]
Looked into it -- Babel is the culprit, and they have already issued a patch: https://github.com/babel/babel/pull/10191

I'm not sure when they will actually release it but  should be soon.  Once that is done we just upgrade our versions of babel being pulled which will in turn upgrade the version of lodash to the post-fix version.

**Comment by reefdog** [comment]
Sounds reasonable.

(I wonder what our attack surface is on this anyway? Maliciously-crafted scrape data that we accidentally parsed as JSON and tried to deep merge? Anyway, just agreeing that our vulnerability is low enough to wait for an official patch.)
