### ISSUE TITLE
Should we suppress all logging in test environment?

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/tech-and-check-alerts#83]
When running tests, logging output in tested code mixes into the test output:

![logger-output](https://user-images.githubusercontent.com/4731/61303443-21d07080-a7ad-11e9-8e7a-ffbfcf49f9cd.png)

I'm thinking we shouldn't configure any loggers when `isTestEnv()`. If a test is failing and we actually need the logger output, we can always disable that check to see what's going on.

Thoughts?

**Comment by reefdog** [comment]
(Specific to the output in the screenshot: our test doesn't _actually_ send an email. The Mailgun API interaction is itself in "test mode", which means the API acts entirely normal except doesn't truly deliver the email. This lets us ensure our interaction is correctly-formatted and passes validation, but without actually sending messages.)

**Comment by slifty** [comment]
What do you think of suppressing info and below, but keeping warnings / errors in test environment?

**Comment by reefdog** [comment]
I'd say suppress it all for now. We shouldn't be debugging via the testing environment.

In the case of needing to _debug the test environment_, we can change that for the duration of our debugging session.

**Comment by reefdog** [comment]
> We can also just route all of it to a test.log rather than console, which allows for debugging as needed without crufting up the console.
>
> I'd like to avoid the need to change code when something fails; I like the test.log with everything (including info) best.

Actually, this sounds good. 👍
