### ISSUE TITLE
Add North Carolina newsletter

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/tech-and-check-alerts#94]
Add the newsletter for the NC-only Twitter list.

**Comment by reefdog** [comment]
@markstencel @ericaryan Is the boilerplate identical for the NC newsletter? If not, could you let me know the modified text?

**Comment by markstencel** [comment]
Will do. Bill is looking at the text for the national alerts (he also has suggestions for subject lines). I'll get you an NC Alert intro as soon as I get his feedback.

**Comment by reefdog** [comment]
@markstencel Did you ever hear back about the boilerplate text for the NC newsletter?
