### ISSUE TITLE
Attributions can contain numbers

### ISSUE THREAD

**Issue by slifty** [TechAndCheck/tech-and-check-alerts#98]
```
BILL CLINTON, 42ND PRESIDENT OF THE UNITED STATES: All of a sudden 25 million more people had healthcare and then the people are out there busting it, sometimes 60 hours a week wind up with their premiums doubled and their coverage cut in half.
```

We need the attribution regular expression to allow for numbers.

**Comment by reefdog** [comment]
For reference: [Asa's existing method for ID'ing speakers](https://github.com/TechAndCheck/tech-and-check-alerts-2018/blob/ab1bb599319f034dbe300d2890b1638df764d89e/cnn_tools/cnn_buster.py#L62-L101).
