### ISSUE TITLE
Populate additional claim metadata

### ISSUE THREAD

**Issue by slifty** [TechAndCheck/tech-and-check-alerts#99]
We also should be storing all the things we trivially have access to which now have claim fields.  Specifically:

* [x] Speaker name
* [x] Speaker affiliation
* [x] Canonical URL
* [x] Scraper name

**Comment by reefdog** [comment]
As long as you're doing this, man oh man do I keep tripping over "scraper code". Is that just because I think of "code" as executable code? Why not something like `scraperName` or `scraperNicknameDanGaveIt` or even just `scraper`?

**Comment by reefdog** [comment]
Delivered by #105 :tada:
